# Generated by Django 5.0.3 on 2024-04-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('materiaPrima', models.CharField(max_length=50)),
                ('manoDeObra', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('precio', models.FloatField(verbose_name='PrecioTotal')),
                ('estado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appVentas.cliente')),
            ],
        ),
    ]
